version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test

workflows:
    build-and-test: 
      jobs:
        - build
    build-and-deploy:
      jobs:
        - build
        - aws-ecs/deploy-service-update:
            cluster-name: arn:aws:ec2:*:*:instance/i-0db512246729173fd 
            docker-image-for-job: circleci/node:10.16.3 
            family: T2-micro 
            requires: 
              - build
